### PR TITLE
Update search.md

### PR DESCRIPTION
**Pull request by kellyelton**
Just mention that only extended data is searchable, not other objects passed into the error

### CODE REVIEW

**Comment by niemyjski** [comment]
I think this is already covered here: https://github.com/exceptionless/docs.exceptionless.com/blob/gh-pages/contents/search.md#q-can-i-search-by-my-custom-extended-data

Thoughts?

**Comment by kellyelton** [comment]
I suppose it is, it's just lacking naming I think. so, those tabs aren't searchable(except the extended data one)? Or are those tabs actually searchable if the property is a simple value?

**Comment by kellyelton** [comment]
Or no wait, they're all kind of the same, except that if it's a complex object it gets its own tab I think?

**Comment by niemyjski** [comment]
Most of our fields of known extended data fields are searchable as per that doc shows what fields are.. but end users custom data will only be searchable if it's of a simple property type (string, boolean, number etc..). The issue with us searching complex objects is two fold:

1. It creates a massive mapping index in elastic search and consumes much more memory.
2. Once the mapping is created it can't be changed. once an changed object is submitted it will error out during submission.. This is why we restrict it to simple types because we detect the type and then suffix the property name with the type (-n, -s, -b)..

**Comment by niemyjski** [comment]
No, anything can be promoted to it's own tab. but our known objects automatically are first class experiences.

**Comment by kellyelton** [comment]
Ok. I hadn't used exceptionless in awhile, looking back though now I realize that I have all these extra tabs because I promoted individual bits of data into tabs. That clears up my confusion actually.

**Comment by niemyjski** [comment]
:), does it make sense to you as an end user what is searchable when you read the docs?

**Comment by kellyelton** [comment]
Yeah. I mean it took a second read the first time I started using it...but the main thing that confused me is I used the hosted exceptionless for one project and the self hosted for something else, and I kind of neglected the one for a few months, and went back and had a bunch of tabs and started assuming tabs were different because I forgot about them. I don't think it was a problem with the docs.

**Pull request closed without merging**
